# Generated by Django 4.1.1 on 2022-12-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GaleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
